---
event:
  name: abi-ian
  template: standard.yaml
graphics:
  display:
    width: 1024
    height: 768
    fullscreen: 0
input:
  touch:
    hide-cursor: false
    touch-retain-time: 150
    touch-retain-distance: 30
zeroconf-listeners:
- name: File Server
  config:
    type: _tailor._tcp.local.
print:
  maximum_prints: 3
social:
  twitter:
    account: "@kilbuckcreekphoto"
  email:
    sender: leif@kilbuckcreek.com
    subject: Your photo from Kilbuck Creek Photo Booth
  print:
    maximum_prints: 3
