---
print-queue:
  interval: 10
interface:
  host: ''
  port: 5000
zeroconf-servers:
- name: File Server
  config:
    type: _tailor._tcp.local.
    description: tailor file server
    properties: {}
    addr: 127.0.0.1
    port: '5000'
