[AccordionItemTitle@Widget]:
    height: 232
    size_hint: 1, None

    canvas:
        Color:
            rgba: 0, 1, 0, 1
        Rectangle:
            size: self.size
            pos: self.pos[0], self.pos[1] - self.height

        Rectangle:
            source: ctx.item.icon_source
            #pos: self.pos[0], self.pos[1] - self.size[1] - ctx.item.icon_size[1] + 18
            pos: self.pos[0], self.pos[1] - self.height
            size: ctx.item.icon_size

    canvas.before:
        Color:
            rgb: 1,0,0

        Rectangle:
            pos: self.pos[0], self.pos[1] - self.height
            size: self.size

        PushMatrix
        Translate:
            xy: self.center_x, self.center_y
        Rotate:
            angle: 90 if ctx.item.orientation == 'horizontal' else 0
            axis: 0, 0, 1
        Translate:
            xy: -self.center_x, -self.center_y

    canvas.after:
        PopMatrix
